In [ ]:
import numpy as np
arr=np.array(2)
print(arr)
type(arr)
print(arr.size)
print(arr.shape)
print(arr.ndim)

2
1
()
0


In [ ]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
print(arr.size)
print(arr.shape)
print(arr.ndim)

[1 2 3]
3
(3,)
1


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.size)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [ ]:
import numpy as np
arr=np.array([[[[[2.3]]]]])
print(arr)
print(arr.size)
print(arr.shape)
print(arr.ndim)

[[[[[2.3]]]]]
1
(1, 1, 1, 1, 1)
5


In [ ]:
import numpy as np
arr=np.array([1,2,11,12])
print(arr[2]+arr[3])

23


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,2])

6


In [ ]:
import numpy as np
arr=np.array(([1,2,3,4]),ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [ ]:
#slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:3])

[2 3]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,1:3])

[5 6]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0:2,1:2])

[[2]
 [5]]


In [ ]:
import numpy as np
arr=np.array([1,2,11,12])
s=(arr[2]+arr[3])
d=(arr[2]-arr[3])
p=(arr[3]*arr[3])
d=(arr[3]/arr[3])
print(s,d,p,d)


23 1.0 144 1.0


In [ ]:
import numpy as np
arr=np.array([1,2,11,4,5,6,7,12])
new_arr=arr.reshape(2,4)
print(new_arr)

[[ 1  2 11  4]
 [ 5  6  7 12]]


In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,56,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51])

In [ ]:
import numpy as np
arr1=np.array([[1,2],[2,3]])
arr2=np.array([[4,5],[6,7]])
print(arr1+arr2)

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1@arr2)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
c_a=np.concatenate((arr1,arr2),axis=1)
print(c_a)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
c_a=np.concatenate((arr1,arr2),axis=0)
print(c_a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
flattened_arr=arr.flatten()
print(flattened_arr)

[ 1  2 11  4  5  6  7 12]


In [ ]:
arr1=np.array([[1,2,5],[3,4,4]])
print(arr1)
print()
transposed_arr=arr1.transpose()
print(transposed_arr)


[[1 2 5]
 [3 4 4]]

[[1 3]
 [2 4]
 [5 4]]


In [ ]:
a=np.array([1+1j,1+0j,2,5,6,2j])
print(a)
print(np.iscomplex(a))
print(np.isreal(a))
print(np.isscalar(a))

[1.+1.j 1.+0.j 2.+0.j 5.+0.j 6.+0.j 0.+2.j]
[ True False False False False  True]
[False  True  True  True  True False]
False


In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.empty(2)

array([1., 1.])